### ISSUE TITLE
Off by one in MessageTask queue

### ISSUE THREAD

**Issue by alltheblinkythings** [Makuna/Task#17]
We pop garbage on the first call to MessageTask::PopMessage, and are always one behind when we pop.

To explain by example:
 - a newly created queue has _indexFront=0 and _indexBack=0.
 - the first call to MessageTask::SendAsyncMessage writes to offset 1 in the queue buffer (_indexBack + 1).  
 - the first call to MessageTask::PopMessage reads from _indexFront, which points to offset 0 in the queue buffer.

**Comment by Makuna** [comment]
https://github.com/Makuna/Task/pull/18

If you could pick up this change and confirm it works for you it would be great.
thanks

**Comment by awegmann** [comment]
Same problem in my project. Would like to use the messaging feature. Please fix the bug.

**Comment by Makuna** [comment]
@awegmann does my change listed above solve it for you?

**Comment by awegmann** [comment]
I didn't try the fix, but I have the same issue. First pop of the queue isn't a valid packet. Every subsequent pop delivers one message behind the head of the message queue.

**Comment by awegmann** [comment]
FYI. I just patched the SendAsyncMessage function as described in pull request #18 . Works perfect for me. So it would be perfect if you accepted the pull request and build a new official version.

**Comment by Makuna** [comment]
I have been just waiting for a confirmation, thanks

**Comment by Makuna** [comment]
New release 1.1.5 has been created with the fix.  
It may take the Arduino Library Manager a day or two to pick up the new release.
