### ISSUE TITLE
Tasktime

### ISSUE THREAD

**Issue by Uweklaus** [Makuna/Task#19]
Hi I use this library in am repository. It makes my live easy using tasks.
Now I want to change the Tasktime of a special task by loading a config file. but it seems that this is not possible. 
What do I do wrong?
Is there a way to change the Tasktime of an individual task?

**Comment by Makuna** [comment]
There is a `setTimeInterval()` that will allow you to change it.

**Comment by Uweklaus** [comment]
Great!! Thanks a lot. Works perfect.
