### ISSUE TITLE
would like to deliver an example

### ISSUE THREAD

**Issue by Uweklaus** [Makuna/Task#25]
I would like to show an example using your gr8 Task library.
[https://github.com/Uweklaus/ESP8266-SensorLights](https://github.com/Uweklaus/ESP8266-SensorLights)

Thanks for your gr8 work

**Comment by Makuna** [comment]
I put a link in the wiki [here](https://github.com/Makuna/Task/wiki/Other-Projects) to your project.  The Wiki can be edited by others so you can elaborate or correct the link if things change.

**Comment by Uweklaus** [comment]
Thanks a lot!
