### ISSUE TITLE
Task frequency

### ISSUE THREAD

**Issue by porkyneal** [Makuna/Task#4]
Is there a way to change a task frequency during runtime?

**Comment by Makuna** [comment]
Yes there is; but it currently isn't obvious or well exposed.
Currently this is a protected field in the task object.  This means that it can be modified within a derived task object.  If you use the Task Macros or create your own task object derived from Task, then within either OnStart(), OnStop(), or OnUpdate() methods of that task you can change this property.
The property is _timeInterval.  

I am leaving this Issue open to track "enhancing" the API to expose this ability in a more supported way.

**Comment by Makuna** [comment]
https://github.com/Makuna/Task/pull/5
