### ISSUE TITLE
esp82666 WDT reboot caused by TaskManager c-tor

### ISSUE THREAD

**Issue by Palatis** [Makuna/Task#6]
a really simple sketch to reproduce the problem.
```
#include <Task.h>

TaskManager Tasks;

void setup() {
  Serial.begin(74880);
  Serial.setDebugOutput(true);
  Serial.println();
  Serial.println(ESP.getResetReason());
  Serial.println(ESP.getResetInfo());

  while (true) {
    Serial.print('.');
    if ((i % 80) == 0)
      Serial.println();
    //wdt_reset();
    delay(500);
  }
}

void loop() {
}
```

normally we don't want to mess around with WDT unless it's really absolutely necessary, the user might make other use with it.

**Comment by Makuna** [comment]
Managing the Watchdog is a core feature of the TaskLibrary as it prescribes actions (like DONT USE delay()) that can cause the watchdog to fire if the user follows the guidelines.

I will look into this, please include what hardware you are using.

**Comment by Makuna** [comment]
Ok, your sketch is invalid, in that it has to things wrong with it.
1) Don't use `delay()`, this library states this many times in the headers, readme, and wiki.  
2) Your `loop()` is missing the `Tasks.Loop()`

With correctly written code, the disable of the software watchdog on Esp8266 is ok.  It was meant to catch people putting long running code in the `setup()`; where it should be avoided.

In general, I prescribe that keep your `setup()` as small as possible, moving long "initialize" into a task and just let it run, and when its done, it can start other tasks.

**Comment by Palatis** [comment]
using delay() is intended, I *don't* want `Tasks`  to `Loop()` while I'm doing something "blocky". instead of removing all tasks and re-add them later (which is difficult to do so because `TaskManager` doesn't expose such an interface), I just don't call `Tasks.Loop()`.

To be more specific, I want to do WiFi.startSmartConfig() on a button press, which shuts down the whole wifi stack and I have to wait for it to finish before I can continue.
I'm using ESPAsyncTCP to handle network connections, disabling WiFi while there're on-going connections will cause esp to throw exception (due to some mysterious framework code I guess... It tries to do checksum after the buffers are freed according to the stack trace...)

so, instead, I just write a flag to EEPROM and call `ESP.reset()`, and let SmartConfig be done in `setup()` before any on-going network activities.

`Tasks.Loop()` is not inside the `loop()` function because it's unrelated to the problem.

I think this is reproducible on all ESP8266 boards, but in my case, I'm using NodeMCU v2.

**Comment by Makuna** [comment]
The task library is aimed at writing code that is not blocky.  That is its goal, of which you are stating you don't want.  Lets discuss this more on the Task gitter channel as I feel we may both be missing something.

https://gitter.im/Makuna/Task

**Comment by Makuna** [comment]
I am pulling the wdt_disable from the contructor completely for Esp8266.  The issue at hand is, for AVR, during Setup there is no watch dog enabled, that was what it was meant to do.  For Esp8266, you can't fully disable the watch dog ever, so by disabling the software watch dog all it does is make all the "hooks" that feed the dog be useless and the hardware watch dog will kick in (6 seconds I believe is its hard coded time); which does not match the AVR experience.  The closest to match is to leave it enabled.  So this is what I will be doing in the next update.

**Comment by Makuna** [comment]
https://github.com/Makuna/Task/pull/7
