### ISSUE TITLE
Handling asyncronous callbacks

### ISSUE THREAD

**Issue by SirUli** [Makuna/Task#9]
Hi,

first a big THANK YOU for this library - absolutely awesome!

I worked through the examples and also have a couple things running on this library and i was wondering how i best would handle asyncronous callbacks. What do i mean with that?

So for example i am getting the data from a light sensor and want to forward it to MQTT. At the same time i want to ensure that a display constantly being updated every 1000ms.

So i wrote a custom Task (like the ButtonTask.h) to run the Sensor Update and finally call a callback. The Callback basically just fires off the following handler:

```cpp
void taskHandleGetTSL2561()
{
  taskManager.StartTask(&taskMqttTSL2561);
}
```

In the _taskMqttTSL2561_ the Task is being stopped again at the end (`taskManager.StopTask(&taskMqttTSL2561);`). This way i am not blocking the display update if this would come in between the sensor reading & MQTT hand-off. The MQTT is fired off 500ms after the task has been started which at least from the idea would allow this to be run properly.

My question is: Is this how this is intended? Or is there a better way to fire off "one time" tasks?

Thanks in advance!

Best Regards,
Uli

**Comment by Makuna** [comment]
You are doing it the correct way.  This library doesn't have anything specific for "one off" tasks, as internally I would do the same thing you do.  
Early on I decided to not put a code burden on every sketch for handling different task handoffs (loop, one-time, flip-flop) and just let the implementer do it if they need it. 

For quick questions like this, just jump on Gitter and ask away.
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/Task?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by SirUli** [comment]
Thanks a lot - that helps! I thought i am overlooking something ;)
